nelmio_api_doc:
    documentation:
        info:
            title: REST API
            description: Zadanie nr 3, Systemy Rozproszone!
            version: 2.6.0
        security:
            - Bearer: []
        components:
            securitySchemes:
                Bearer:          
                    type: apiKey
                    description: 'Authorization: Bearer {jwt}'
                    name: Authorization
                    in: header            
            schemas:
                User:
                    type: object
                    properties:
                        username:
                            type: string
                            example: "john.doe"
                        password:
                            type: string
                            example: "john.doe"
                NewUser:
                    type: object
                    properties:
                        username:
                            type: string
                            example: "john.doe"
                        password:
                            type: string
                            example: "john.doe" 
                        roles:
                            type: array
                            items:
                                type: string
                            example: ["ROLE_ADMIN"]     
                Roles:
                    type: object
                    properties:
                        roles:
                            type: array
                            items:
                                type: string
                            example: ["ROLE_USER", "ROLE_ADMIN"]                       
                Teacher:
                    type: object
                    properties:
                        id:
                            type: integer
                        name:
                            type: string
                        email:
                            type: string
                        specialization:
                            type: string
                        login:
                            $ref: '#/components/schemas/User'
                Student:
                    type: object
                    properties:
                        id:
                            name: integer
                            example: "John Doe" 
                        name:
                            type: string
                        email:
                            type: string
                        group:
                            type: string
                        login:
                            $ref: '#/components/schemas/User'
                NewStudent:
                    type: object
                    properties:
                        name:
                            type: string
                            example: "John Doe"
                        email:
                            type: string
                            example: "johndoe@example.com" 
                        username:
                            type: string
                            example: "john.doe"
                        password:
                            type: string
                            example: "password"
                NewTeacher:
                    type: object
                    properties:
                        name:
                            type: string
                            example: "John Doe"
                        email:
                            type: string
                            example: "johndoe@example.com" 
                        specialization:
                            type: string
                            example: "IT" 
                        username:
                            type: string
                            example: "john.doe"
                        password:
                            type: string
                            example: "password"    
                EditStudent:
                    type: object
                    properties:
                        name:
                            type: string
                            example: "John Doe"
                        email:
                            type: string
                            example: "johndoe@example.com" 
                EditTeacher:
                    type: object
                    properties:
                        name:
                            type: string
                            example: "John Doe"
                        email:
                            type: string
                            example: "johndoe@example.com" 
                        specialization:
                            type: string
                            example: "IT"                                           
                Course:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 4002
                        title:
                            type: string
                            example: "Sieci komputerowe"
                        description:
                            type: string
                            example: "Internet, sieci, protokoły"
                        teacher:
                            $ref: '#/components/schemas/Teacher'
                        capacity:
                            type: integer  
                            example: 10
                        active:
                            type: boolean
                            example: true  
                NewCourse:
                    type: object
                    properties:
                        title:
                            type: string
                            example: "Nazwa kursu"
                        description:
                            type: string
                            example: "Opis kursu"
                        teacher_id:
                            type: integer
                            example: 2000                        
                        capacity:
                            type: integer  
                            example: 10
                        active:
                            type: boolean
                            example: true 
                    required:
                        - title
                        - description
                        - teacher_id  
                        - capacity
                        - active
                EditCourse:
                    type: object
                    properties:
                        title:
                            type: string
                            example: "Nazwa kursu"
                        description:
                            type: string
                            example: "Opis kursu"
                        teacher_id:
                            type: integer
                            example: 2000                        
                        capacity:
                            type: integer  
                            example: 10
                        active:
                            type: boolean
                            example: true
                Enrollment:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 5002
                        student:
                            $ref: '#/components/schemas/Student'
                        course:
                            $ref: '#/components/schemas/Course'
                        grade:
                            type: integer
                            example: 5
                NewEnrollment:
                    type: object
                    properties:
                        student_id:
                            type: integer
                            example: 3000
                        course_id:
                            type: integer
                            example: 4002
                    required:
                        - student_id
                        - course_id
                EditEnrollment:
                    type: object
                    properties:
                        student_id:
                            type: integer
                            example: 3000
                        course_id:
                            type: integer
                            example: 4002
                        grade:
                            type: integer
                            example: 5
                EnrollCourse:
                    type: object
                    properties:
                        course_id:
                            type: integer
                            example: 4000
                Grade:
                    type: object
                    properties:
                        grade:
                            type: integer
                            example: 5
                    required:
                        - grade
                        

                                                      
                
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
