security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # definicja jak użytkownicy sa ładowani z bazy danych, jaka klasa i jaki identyfikator
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    # Firewall określa, jakie zasady bezpieczeństwa są stosowane na określonych ścieżkach
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
            access_denied_handler: App\Security\AccessDeniedHandler

        main:
            stateless: true
            provider: app_user_provider

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TEACHER, ROLE_STUDENT, ROLE_USER]
        ROLE_TEACHER: [ROLE_USER]
        ROLE_STUDENT: [ROLE_USER]

    access_control:
        # Public endpoints
        - { path: ^/api/login, roles: PUBLIC_ACCESS } 
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }      

        # Kursy: ROLE_TEACHER
        - { path: ^/api/courses, roles: ROLE_TEACHER }

        # Zapisy na Kursy: ROLE_ADMIN
        - { path: ^/api/enrollments, roles: ROLE_ADMIN }

        # Akcja dla studenta: ROLE_STUDENT
        - { path: ^/api/students/\d+/enrollments, roles: ROLE_STUDENT }
        - { path: ^/api/students/enrollments/\d+/grade, roles: ROLE_STUDENT }

        # Studenci: ROLE_ADMIN
        - { path: ^/api/students, roles: ROLE_ADMIN }

        # Akcje dla nauczyciela: ROLE_TEACHER
        - { path: ^/api/teachers/courses, roles: ROLE_TEACHER }
        - { path: ^/api/teachers/courses/\d+/capacity, roles: ROLE_TEACHER }
        - { path: ^/api/teachers/courses/\d+/block, roles: ROLE_TEACHER }
        - { path: ^/api/teachers/courses/\d+/unblock, roles: ROLE_TEACHER }
        - { path: ^/api/teachers/courses/\d+/students, roles: ROLE_TEACHER }
        - { path: ^/api/teachers/enrollments/\d+/grade, roles: ROLE_TEACHER }

        # Nauczyciele, użytkownicy: ROLE_ADMIN
        - { path: ^/api/teachers, roles: ROLE_ADMIN }
        - { path: ^/api/users, roles: ROLE_ADMIN }


        # Default deny all
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
