controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login
    controller: App\Controller\SecurityController::login
    methods: POST

# api_test:
#     path: /api/test
#     controller: App\Controller\ApiTestController::index
#     methods: GET

