controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# api_test:
#     path: /api/test
#     controller: App\Controller\ApiTestController::index
#     methods: GET

